version: "3.8"
services:
  slate:
    image: slatedocs/slate:v2.13.1
    ports:
      - "4567:4567"
    command: "serve"
    volumes:
      - ./source:/srv/slate/source
      - ./build:/srv/slate/build
