# Esse é o fluxo de continuous deployment (CD),
# com o objetivo final de atualizar a documentação do Fintera Recebíveis no GitHub Pages.

name: CD

# O fluxo é disparado apenas quando houver um push ou pull request mergeado na branch `main`.
on:
  push:
    branches: [ main ]

  # Permitir rodar esse fluxo manualmente na interface do GitHub Actions.
  workflow_dispatch:

# Permissões necessárias para usar o token do GitHub e realizar o deploy no GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Definição do fluxo em si de CD.
jobs:
  deploy:
    # Ao final do fluxo irá printar a URL da documentação.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório para o $GITHUB_WORKSPACE, onde o job tem acesso ao código.
      - name: Checkout
        uses: actions/checkout@v3

      # Inicia o container do Slate, pois iremos fazer o build dentro do container que já possui todas as dependências necessárias.
      - name: Start Docker Compose
        run: docker-compose up -d

      # Realizar o build dos arquivos da documentação que estão em ./source para a pasta ./build.
      - name: Build docs
        run: docker-compose exec -T slate sh -c 'bundle exec middleman build'

      # Realizar a configuração do GitHub Pages.
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Envia todos os arquivos da pasta ./build/ para o GitHub Pages.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/'

      # Faz o deploy do GitHub Pages para atualizar o mesmo.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
